### ISSUE TITLE
Error in Tests... somewhere

### ISSUE THREAD

**Issue by steveafrost** [learn-co-curriculum/react-prop-types-lab#10]
Getting held up on this fail on my own solution & on official solution. If I comment out that test, the next one fails, if I comment out the next one, the one after that fails. I think it is something with the isRequiredPropTypeError?

  1) <Product /> `name` prop should be required:
     Error: This prop should be required.
      at assert (node_modules/expect/lib/assert.js:29:9)
      at Expectation.toExist (node_modules/expect/lib/Expectation.js:52:28)
      at Context.<anonymous> (test/index-test.js:52:52)

**Comment by ipc103** [comment]
closed by #13
