### ISSUE TITLE
Test failure due to hardcoded error

### ISSUE THREAD

**Issue by Traci7822** [learn-co-curriculum/react-prop-types-lab#11]
Test error:

1) <Product /> &#96;name&#96; prop should be required:                                            
     Error: This prop should be required.                                                   
      at assert (node_modules/expect/lib/assert.js:29:9)                                    
      at Expectation.toExist (node_modules/expect/lib/Expectation.js:52:28)                 
      at Context.<anonymous> (test/index-test.js:52:52)

Resolution:
comment out line 52  in index-test.js:
expect(isRequiredPropTypeError(spy, 'name')).toBeTruthy(ERRORS.PROP_IS_REQUIRED);

**Comment by kwebster2** [comment]
@aturkewi 
Fixed by #13

**Comment by ipc103** [comment]
closed by #13
